// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Infra.Data.Context;

namespace Sistema.Infra.Data.Migrations
{
    [DbContext(typeof(SistemaContext))]
    partial class SistemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sistema.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Cliente_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataNascimento")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<int>("Sexo");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("Cliente_Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("Estoque_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estoque_QTDE")
                        .HasMaxLength(400);

                    b.Property<int?>("ProdutosProduto_Id");

                    b.HasKey("Estoque_Id");

                    b.HasIndex("ProdutosProduto_Id");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Item_Pedido", b =>
                {
                    b.Property<int>("Produto_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemPed_Nome")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<int>("ItemPed_QTDE")
                        .HasMaxLength(400);

                    b.Property<int>("ItemPed_Valor");

                    b.Property<int>("Pedido_Id");

                    b.Property<int?>("PedidosCliente_Id");

                    b.Property<int?>("ProdutosProduto_Id");

                    b.HasKey("Produto_Id");

                    b.HasAlternateKey("Pedido_Id");

                    b.HasIndex("PedidosCliente_Id");

                    b.HasIndex("ProdutosProduto_Id");

                    b.ToTable("Itens_Pedido");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Cliente_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Cliente_Id1");

                    b.Property<string>("Pedido_Data")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<int>("Pedido_Id");

                    b.Property<string>("Pedido_QTDE")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Pedido_Valor")
                        .IsRequired();

                    b.HasKey("Cliente_Id");

                    b.HasAlternateKey("Pedido_Id");

                    b.HasIndex("Cliente_Id1");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Produto_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Produto_Nome")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Produto_Valor")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("Produto_Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("Sistema.Domain.Entities.Produto", "Produtos")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutosProduto_Id");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Item_Pedido", b =>
                {
                    b.HasOne("Sistema.Domain.Entities.Pedido", "Pedidos")
                        .WithMany("Itens_Pedido")
                        .HasForeignKey("PedidosCliente_Id");

                    b.HasOne("Sistema.Domain.Entities.Produto", "Produtos")
                        .WithMany("Itens_Pedido")
                        .HasForeignKey("ProdutosProduto_Id");
                });

            modelBuilder.Entity("Sistema.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Sistema.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cliente_Id1");
                });
#pragma warning restore 612, 618
        }
    }
}
